In [1]:
import numpy as np

In [2]:
bpr=5
apr=7
gp=np.array([4,5])

In [3]:
b_public = (gp*bpr)
a_public = (gp*apr)
a_public,b_public

(array([28, 35]), array([20, 25]))

In [4]:
secret_A=(apr*b_public)
secret_B=(bpr*a_public)
k=secret_A
k

array([140, 175])

In [5]:
msg=np.array([78,65])

c=msg+(k*b_public)
c

array([2878, 4440])

In [6]:
d=k*bpr*gp
plt=c-d
plt

array([78, 65])